### ISSUE TITLE
做了一些优化

### ISSUE THREAD

**Issue by artisanbox** [jic999/moon-web-start#1]
hi，我在作者的代码基础上做了一些优化
新增了搜索词的联想，
优化了手机端 ui
修复了手机端 drag 点击 bug
调整了部分的页面显示
现在部署在了：comecome.cc
后面我会整理提交一个 pr，感谢作者。

**Comment by auwen** [comment]
感谢贡献，说实话这个issue令我十分意外，因为到目前为止，该项目除了我自己使用之外，几乎没有宣传过，没想到居然有人能够发现并贡献它😆

**Comment by leslieyin** [comment]
> hi，我在作者的代码基础上做了一些优化
> 新增了搜索词的联想，
> 优化了手机端 ui
> 修复了手机端 drag 点击 bug
> 调整了部分的页面显示
> 现在部署在了：comecome.cc
> 后面我会整理提交一个 pr，感谢作者。

大佬，优化部分可否pr下 感谢 😊

**Comment by artisanbox** [comment]
好的，代码还在我本地，周末我整理一下，工作比较忙

**Comment by leslieyin** [comment]
感谢大佬🧍‍♂️

**Comment by artisanbox** [comment]
> 感谢大佬🧍‍♂️

兑现诺然，拖了很久了，今天好好整理了一下，可能还有些问题。

https://github.com/jic999/moon-web-start/pull/3

**Comment by auwen** [comment]
pr已合并，在这之后我又发现并修复了一些之前忽略的问题😄，**目前**[最新的提交](https://github.com/jic999/moon-web-start/commit/0982e5f901136bbab8e79c3db16882e2732f9523)暂时没发现什么bug，如果没有其他问题的话我将关闭该issue💖

**Comment by artisanbox** [comment]
💪🏻，新加网址输入框为空时可能需要判断一下，否则加入的空连接

**Comment by auwen** [comment]
> 💪🏻，新加网址输入框为空时可能需要判断一下，否则加入的空连接

好的，一直是我自己在用，以至于几乎忽略了这个最简单的问题😆

**Comment by artisanbox** [comment]
嗯嗯，还有一个bug，就是重置数据的时候，需要设置判断 cateIndex 是否超过了已有个 length，需要做一下处理。
复现：在设置页面下，新增一个大分类后，点击这个分类，这个时候重置数据。

**Comment by auwen** [comment]
> 嗯嗯，还有一个bug，就是重置数据的时候，需要设置判断 cateIndex 是否超过了已有个 length，需要做一下处理。 复现：在设置页面下，新增一个大分类后，点击这个分类，这个时候重置数据。

这个确实没考虑到，我改成重置数据后索引归零了。现在我把`setting`的类型进行了调整，便于添加和维护更多设置项。然后`site`的标签从`div`改为了`a`，这样可以右键点击选择操作；现在`setting`路由作为了主页的子路由，以防组件重复渲染；网站`favicon`加载失败后会根据名称生成图案，以避免一个单调的地球。还有什么问题和想法，欢迎交流😊

**Comment by artisanbox** [comment]
应该没啥问题了，其他的都是细节。
