### ISSUE TITLE
请问可以制作个docker镜像吗？

### ISSUE THREAD

**Issue by dianso** [jic999/moon-web-start#10]
请问可以制作个docker镜像吗？

**Comment by dianso** [comment]
找到个fork的
github.com/Rod0320/web-start-vue

**Comment by dianso** [comment]
要是能保存书签到服务器就好了

**Comment by dianso** [comment]
我是这样做的
Dockerfile文件
```bash
# 使用一个基础的Node.js镜像
FROM node:18-alpine

# 复制当前目录所有文件到 /aap下面
COPY . /app

# 设置主目录为 / app
WORKDIR /app

# 安装依赖
RUN npm install

# 打包
RUN npm run build

CMD ["npm", "run", "preview"]
```

修改package.json

    "preview": "vite preview",
改成
    "preview": "vite preview --port 1888",

docker build -t moon-web-start .

docker-compose.yml文件
```bash
version: "3.8"

services:
  moon-web-start:
    image: moon-web-start
    container_name: moon-web-start
    restart: always
    ports:
      - 50050:1888
```


docker-compose up -d

**Comment by dianso** [comment]
这个也是修改自这个项目吧，我看有同步功能。

https://0x3.com/

其实增加一个导出到本地的json文件就行

**Comment by auwen** [comment]
docker 镜像等我过段时间有空了尝试整一个，你可以先参考那个 fork。

数据目前是可以导出为 json 文件的，由于还没有开发后端服务，所以暂时无法同步。后端服务我计划使用 `koa` 开发，主要做同步数据和爬取favicon 两个功能，具体实现可能要再过段时间。当然，如果你有兴趣的话，欢迎提交 pr😆

然后，`README.md` 里面也提到了，0x3 是我之前一直在用的，但貌似没有开源，所以我参考 0x3 的样式做了这个项目，而不是 0x3 修改自这个项目🤣
