### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by ggb6070** [jic999/moon-web-start#13]
能否增加显示“秒”时间的功能？

**Comment by auwen** [comment]
最近的提交 https://github.com/jic999/moon-web-start/commit/e102a79220327424175917fa858425c5e919de76 支持了显示秒钟，可自行在设置中打开

**Comment by 172151295** [comment]
> 最近的提交 https://github.com/jic999/moon-web-start/commit/e102a79220327424175917fa858425c5e919de76 支持了显示秒钟，可自行在设置中打开

可否搞一个简单的后端

**Comment by ggb6070** [comment]
> 最近的提交 [e102a79](https://github.com/jic999/moon-web-start/commit/e102a79220327424175917fa858425c5e919de76) 支持了显示秒钟，可自行在设置中打开

感谢大佬
