### ISSUE TITLE
docker 部署如何实现数据持久化

### ISSUE THREAD

**Issue by oh1h0ney** [jic999/moon-web-start#4]
编辑后的数据存放在什么位置？是否可以创建卷挂载这些数据，以实现在不同设备上的数据同步？
目前观察挂载了 src 目录后，在 A、B 设备上打开的数据并不同步

**Comment by auwen** [comment]
目前暂时没有开发后端服务，自定义的数据存储在浏览器的 `localStorage` 中，需要手动导入导出数据来实现同步。

要想实现自动同步并为多用户提供服务，需要一个数据库。如果只是自己使用的话，可以开启一个 `node` 服务，把数据写入到一个 `json` 文件中，以实现数据持久化存储。
