### ISSUE TITLE
能支持密码吗？穿透出去太危险了

### ISSUE THREAD

**Issue by gsh456** [jic999/moon-web-start#5]

**Comment by gsh456** [comment]
编辑管理的时候需要密码就行

**Comment by auwen** [comment]
抱歉我不太懂你的意思，自定义数据不会上传到服务器，每个人编辑的都是自己的本地数据。所以至少目前看来，我不太理解为什么需要一个密码

**Comment by gsh456** [comment]
哦，我大概明白了，所有数据都保存在用户浏览器本地，如果用户更换浏览器或者电脑的话，数据就需要重新配置(或导入导出)。我最开始使用的时候以为和flare或者homarr的使用方式一样呢，还是习惯于他们的方式。

**Comment by auwen** [comment]
是的，后面可能会开发后端服务，通过邮箱或secret同步数据
