### ISSUE TITLE
问题与建议

### ISSUE THREAD

**Issue by ebookuser** [jic999/moon-web-start#6]
问题：1.一级分类的导航条，在有触屏的屏幕上可以拖动，但在非触屏设备上超过页面可显示的范围的分类就会因为不在页面中，而无法选择中，？
2.fork后运行action，搭建出来的页面是空白，请求应该如何使用GitHub pages搭建？
功能建议：请问能否添加一个针对页面内内容的搜索？

**Comment by auwen** [comment]
感谢反馈。

问题1：这是因为导航栏隐藏了滚动条，按住 `shift`后滚动鼠标即可进行操作，当然你也可以选择将滚动条显示出来。

问题2：你如果在空白页打开控制台的话，可以看到请求资源的url是有问题的，这与 `vite.config.ts`中的`base`有关。我的处理方式是在 `github-pages.yml`中新增了一个环境变量`REPOSITORY`，然后在`vite.config.ts`中根据该变量设置`base`值。当然这样做的话静态资源的路径也要进行相应调整。

![](https://cdn.jsdelivr.net/gh/jic999/images/blog/20231021102900.png)

页面内容搜索，你的意思是对已有的网页名称进行本地搜索吗？

**Comment by ebookuser** [comment]
问题1：请问如何将滚动条显示出来？

问题2：请问可以在readerme中增加一节关于如何部署在GitHubpage等相关网站的说明吗？

Q：页面内容搜索，你的意思是对已有的网页名称进行本地搜索吗？
A：是的，考虑到如果网页内书签数量很多的情况下，搜索名称或许会更加方便。

**Comment by ebookuser** [comment]
问题1：请问如何将滚动条显示出来？

问题2：请问可以在readerme中增加一节关于如何部署在GitHubpage等相关网站的说明吗？

Q：页面内容搜索，你的意思是对已有的网页名称进行本地搜索吗？
A：是的，考虑到如果网页内书签数量很多的情况下，搜索名称或许会更加方便。
